version: "3.1"

services:

  rp:
<<<<<<< HEAD
    image: dockerownc_rp
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
=======
    build:
      context: .
      dockerfile: Dockerfile-nginx
>>>>>>> 1f6d60edd8653c5ddf0a0401ad99079d4c76f760
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_nginx-rp:/etc/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextc_data:/var/www/

<<<<<<< HEAD
#  certbot:
#    image: certbot/certbot
#    command: certonly --webroot -w /var/www/letsencrypt -d 1nfr.com
#    volumes:
#      - nextc_data:/var/www/
#      - nextc_letsencrypt:/etc/letsencrypt/

#  fpm:
#    build:
#      context: .
#      dockerfile: Dockerfile-fpm    
#    volumes:
#      - nextc_data:/var/www/
#      - nextc_fpm:/etc/php
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    links:
#      - db
#    depends_on:
#      - db
#    restart: always
=======
  certbot:
    image: certbot/certbot
    command: certonly --dry-run
    volumes:
      - nextc_certbot:/var/www/certbot/
      - nextc_letsencrypt:/etc/letsencrypt/

  fpm:
    build:
      context: .
      dockerfile: Dockerfile-fpm    
    volumes:
      - nextc_data:/var/www/
      - nextc_fpm:/etc/php/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - db
    depends_on:
      - db
    restart: always
>>>>>>> 1f6d60edd8653c5ddf0a0401ad99079d4c76f760

  web:
    image: dockerownc_web
#    build:
#      context: .
#      dockerfile: Dockerfile-nextcloud
    volumes:
      - nextc_www:/var/www/
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_apache2:/etc/apache2/
      - nextc_log_web:/var/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

  db:
    image: mariadb:10.1
    volumes:
      - nextc_db:/var/lib/mysql/
      - nextc_db_backup:/srv/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - db_pwd 
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
      MYSQL_DATABASE: owncloud
      MYSQL_USER: ownc7
      MYSQL_PASSWORD_FILE: /run/secrets/db_pwd

secrets:
  db_pwd:
    file: ./db_pwd.txt

volumes:
  nextc_www:
  nextc_apache2:
  nextc_letsencrypt:
  nextc_db:
  nextc_db_backup:
  nextc_log_web:
  nextc_nginx-rp:
  nextc_fpm:
  nextc_data:
