---
version: "3.7"

services:

  rp:
    image: nginx:1.19
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 60M
        reservations:
          memory: 60M
          cpus: '0.25'
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 3s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_nginx-rp:/etc/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextc_certbot_root:/var/www/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/healthz"]
    networks:
      - nc_net
      - int_net


  web:
    image: leschard/nextcloud
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 400M
        reservations:
          memory: 300M
          cpus: '0.5'
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 3s
    volumes:
      - nextc_www:/var/www/
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_apache2:/etc/apache2/
      - nextc_log_web:/var/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    networks:
      - nc_net

  db:
    image: mariadb:10.5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 200M
        reservations:
          memory: 200M
          cpus: '0.5'
    volumes:
      - nextc_db:/var/lib/mysql/
      - nextc_db_backup:/srv/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - db_pwd
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
      MYSQL_DATABASE: owncloud
      MYSQL_USER: ownc7
      MYSQL_PASSWORD_FILE: /run/secrets/db_pwd
    networks:
      - nc_net

  redis:
    image: 'bitnami/redis:6.0'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          memory: 50M
          cpus: '0.25'
      update_config:
        order: start-first
        failure_action: rollback
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - nextc_redis:/bitnami/redis/data
    networks:
      - nc_net

networks:
  int_net:
    external: true
    name: int_net
  nc_net:

secrets:
  db_pwd:
    file: ./db_pwd.txt

volumes:
  nextc_www:
  nextc_apache2:
  nextc_letsencrypt:
  nextc_db:
  nextc_db_backup:
  nextc_log_web:
  nextc_nginx-rp:
  nextc_fpm:
  nextc_certbot_root:
  nextc_redis:
  data:
  apps:
  config:
  etc_apache2:
  db:
  db_backup:
  log_web:
