version: "3.4"

services:

  rp:
    image: leschard/rp
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 100M
      update_config:
        order: start-first
        failure_action: rollback
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_nginx-rp:/etc/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextc_certbot_root:/var/www/

  web:
    image: leschard/nextcloud
#    build:
#      context: .
#      dockerfile: Dockerfile-nextcloud
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 400M
    volumes:
      - nextc_www:/var/www/
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_apache2:/etc/apache2/
      - nextc_log_web:/var/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

  db:
    image: mariadb:10.1
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 300M
    volumes:
      - nextc_db:/var/lib/mysql/
      - nextc_db_backup:/srv/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - db_pwd 
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
      MYSQL_DATABASE: owncloud
      MYSQL_USER: ownc7
      MYSQL_PASSWORD_FILE: /run/secrets/db_pwd

secrets:
  db_pwd:
    file: ./db_pwd.txt

volumes:
  nextc_www:
  nextc_apache2:
  nextc_letsencrypt:
  nextc_db:
  nextc_db_backup:
  nextc_log_web:
  nextc_nginx-rp:
  nextc_fpm:
  nextc_certbot_root:
