version: "3.7"

services:

  rp:
    image: nginx:1.19
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 60M
        reservations:
          memory: 60M
          cpus: '0.25'
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 3s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_nginx-rp:/etc/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextc_certbot_root:/var/www/
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
    networks:
      - nc_net
      - int_net


  web:
    image: leschard/nextcloud
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 400M
        reservations:
          memory: 300M
          cpus: '0.5'
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 3s
    volumes:
      - nextc_www:/var/www/
      - nextc_letsencrypt:/etc/letsencrypt/
      - nextc_apache2:/etc/apache2/
      - nextc_log_web:/var/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    networks:
      - nc_net

  db:
    image: mariadb:10.4
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 200M
        reservations:
          memory: 200M
          cpus: '0.5'
    volumes:
      - nextc_db:/var/lib/mysql/
      - nextc_db_backup:/srv/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - db_pwd
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
      MYSQL_DATABASE: owncloud
      MYSQL_USER: ownc7
      MYSQL_PASSWORD_FILE: /run/secrets/db_pwd
    networks:
      - nc_net
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -u
        - root
        - -p$$(cat /var/run/secrets/db_pwd)

#  web-nc:
#    image: nextcloud:15
#    deploy:
#      resources:
#        limits:
#          cpus: '3'
#          memory: 400M
#      update_config:
#        order: start-first
#        failure_action: rollback
#      restart_policy:
#        condition: on-failure
#    volumes:
#      - data:/var/www/html/data/
#      - apps:/var/www/html/apps/
#      - config:/var/www/html/config/
#      - etc_apache2:/etc/apache2/
#      - log_web:/var/log/
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#    networks:
#      - nc_net
#      - int_net

#  db-nc:
#    image: mariadb:10.4
#    deploy:
#      resources:
#        limits:
#          cpus: '3'
#          memory: 300M
#    volumes:
#      - db:/var/lib/mysql/
#      - db_backup:/srv/
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    secrets:
#      - db_pwd
#    environment:
#      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
#      MYSQL_DATABASE: owncloud
#      MYSQL_USER: ownc7
#      MYSQL_PASSWORD_FILE: /run/secrets/db_pwd
#    networks:
#      - nc_net
#    healthcheck:
#      test: >
#        ["CMD", "mysqladmin", "ping",
#        "-u", "root", "-p$$(cat /var/run/secrets/db_pwd)"]

networks:
  int_net:
    external:
      name: int_net
  nc_net:

secrets:
  db_pwd:
    file: ./db_pwd.txt

volumes:
  nextc_www:
  nextc_apache2:
  nextc_letsencrypt:
  nextc_db:
  nextc_db_backup:
  nextc_log_web:
  nextc_nginx-rp:
  nextc_fpm:
  nextc_certbot_root:
  data:
  apps:
  config:
  etc_apache2:
  db:
  db_backup:
  log_web:
